//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArtWebsite
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.Label AdminMessage;
        protected global::System.Web.UI.WebControls.Label LabelArtworkTitle;
        protected global::System.Web.UI.WebControls.TextBox ArtworkTitle;
        protected global::System.Web.UI.WebControls.Label LabelArtworkDescription;
        protected global::System.Web.UI.WebControls.TextBox ArtworkDescription;
        protected global::System.Web.UI.WebControls.Label LabelArtworkCategory;
        protected global::System.Web.UI.WebControls.TextBox ArtworkCategory;
        protected global::System.Web.UI.WebControls.Label LabelArtworkImagePath;
        protected global::System.Web.UI.WebControls.TextBox ArtworkImagePath;
        protected global::System.Web.UI.WebControls.Button AddArtworkButton;
        protected global::System.Web.UI.WebControls.Label LabelPostTitle;
        protected global::System.Web.UI.WebControls.TextBox PostTitle;
        protected global::System.Web.UI.WebControls.Label LabelPostContent;
        protected global::System.Web.UI.WebControls.TextBox PostContent;
        protected global::System.Web.UI.WebControls.Label LabelPostDate;
        protected global::System.Web.UI.WebControls.TextBox PostDate;
        protected global::System.Web.UI.WebControls.Button AddPostButton;
    }
}
